environments:
  - OE # Outdoor main Entrance
  - OB # Outdoor MICAS Balcony
  - IL\scanning\868-ULA # Indoor Lab
  - IC # Indoor Cafeteria 

num_antennas: 32
num_sub_carriers: 100
data_carriers:
  - 51
  - 52
#antenna_vector = [1  2  3  4  5  6  7  8  13 14 15 16 11 12 9  10 ...
#                  17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32];
# antenna idx gotten from the BS -> cable idx (i.e. physical antenna sequence)
ant_to_cable_mapping :
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  13: 9
  14: 10
  15: 11
  16: 12
  11: 13
  12: 14
  9: 15
  10: 16
  17: 17
  18: 18
  19: 19
  20: 20
  21: 21
  22: 22
  23: 23
  24: 24
  25: 25
  26: 26
  27: 27
  28: 28
  29: 29
  30: 30
  31: 31
  32: 32